name: Run with project

on:
  push: {}
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Gradle
        run: ./gradlew publishToMavenLocal

      - uses: actions/upload-artifact@v2
        with:
          name: maven-repository
          path: ~/.m2/repository

  example:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        gradle:
          - "4.0"
          - "5.0"
          - "6.0"
          - "7.0"
        project:
          - simplest-cpw
          - simplest-forge
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/download-artifact@v2
        with:
          name: maven-repository
          path: ~/.m2/repository

      - name: Setup Gradle Wrapper
        working-directory: test-projects/${{ matrix.project }}
        run: |
          touch empty
          ../../gradlew --build-file=empty wrapper --gradle-version=${{ matrix.gradle }}
          ./gradlew --build-file=empty wrapper
          rm empty

      - name: Run Build Task
        working-directory: test-projects/${{ matrix.project }}
        run: ./gradlew build
